# Generated by Django 6.0.4 on 2026-04-14 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.URLField(unique=True)),
                ('local_path', models.TextField(blank=True)),
                ('tech_stack', models.CharField(choices=[('django', 'Django'), ('fastapi', 'FastAPI'), ('react_frontend', 'React (frontend)'), ('node_backend', 'Node.js (backend)'), ('react_native', 'React Native'), ('java_app', 'Java app'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('readme_title', models.CharField(blank=True, max_length=512)),
                ('readme_tagline', models.CharField(blank=True, max_length=512)),
                ('readme_table_of_contents', models.TextField(blank=True)),
                ('readme_description', models.TextField(blank=True)),
                ('readme_code_structure', models.TextField(blank=True)),
                ('readme_future_improvements', models.TextField(blank=True)),
                ('readme_full', models.TextField(blank=True)),
                ('readme_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('ingested', 'Ingested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField(help_text='Path relative to the cloned repo root.')),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.BigIntegerField()),
                ('is_selected', models.BooleanField(default=True)),
                ('selection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core_backend.repository')),
            ],
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(choices=[('file', 'File'), ('class', 'Class'), ('function', 'Function'), ('other', 'Other')], default='other', max_length=16)),
                ('symbol_name', models.CharField(blank=True, max_length=255)),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core_backend.filemetadata')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core_backend.repository')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=128)),
                ('agent_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_outputs', to='core_backend.repository')),
            ],
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['repository', 'extension'], name='core_backen_reposit_4ce4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['repository', 'size_bytes'], name='core_backen_reposit_cbb325_idx'),
        ),
        migrations.AddConstraint(
            model_name='filemetadata',
            constraint=models.UniqueConstraint(fields=('repository', 'file_path'), name='uniq_repo_file_path'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['repository', 'chunk_type'], name='core_backen_reposit_2adb75_idx'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['repository', 'file'], name='core_backen_reposit_fea8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='agentoutput',
            index=models.Index(fields=['repository', 'agent_name'], name='core_backen_reposit_3a0ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentoutput',
            index=models.Index(fields=['repository', 'created_at'], name='core_backen_reposit_6cc5f2_idx'),
        ),
    ]
