# Generated by Django 6.0.4 on 2026-04-14 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=128)),
                ('agent_version', models.CharField(blank=True, max_length=64)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_execution_logs', to='core_backend.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repository', 'agent_name'], name='core_backen_reposit_afb971_idx'), models.Index(fields=['repository', 'created_at'], name='core_backen_reposit_512d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadmeGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.URLField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=16)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_cost_estimate_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readme_generation_logs', to='core_backend.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo_url', 'created_at'], name='core_backen_repo_ur_9109e7_idx'), models.Index(fields=['repository', 'created_at'], name='core_backen_reposit_0b117a_idx'), models.Index(fields=['status', 'created_at'], name='core_backen_status_0343dc_idx')],
            },
        ),
    ]
