# Generated by Django 6.0.4 on 2026-04-14 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_agentexecutionlog_readmegenerationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadmeGenerationMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.URLField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=16)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_execution_time_ms', models.IntegerField(default=0)),
                ('agent_logs', models.JSONField(blank=True, default=dict)),
                ('llm_calls', models.JSONField(blank=True, default=list)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('readme_content', models.TextField(blank=True)),
                ('readme_sections', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('failed_step', models.CharField(blank=True, max_length=128)),
                ('detected_tech_stack', models.JSONField(blank=True, default=dict)),
                ('total_files_processed', models.IntegerField(default=0)),
                ('total_chunks_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='agentexecutionlog',
            name='core_backen_reposit_afb971_idx',
        ),
        migrations.RemoveIndex(
            model_name='agentexecutionlog',
            name='core_backen_reposit_512d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='readmegenerationlog',
            name='core_backen_repo_ur_9109e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='readmegenerationlog',
            name='core_backen_reposit_0b117a_idx',
        ),
        migrations.RemoveIndex(
            model_name='readmegenerationlog',
            name='core_backen_status_0343dc_idx',
        ),
        migrations.AddField(
            model_name='readmegenerationmonitor',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readme_generation_monitors', to='core_backend.repository'),
        ),
        migrations.RemoveField(
            model_name='agentexecutionlog',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='readmegenerationlog',
            name='repository',
        ),
        migrations.AddIndex(
            model_name='readmegenerationmonitor',
            index=models.Index(fields=['repo_url', 'created_at'], name='core_backen_repo_ur_458b36_idx'),
        ),
        migrations.AddIndex(
            model_name='readmegenerationmonitor',
            index=models.Index(fields=['repository', 'created_at'], name='core_backen_reposit_1748af_idx'),
        ),
        migrations.AddIndex(
            model_name='readmegenerationmonitor',
            index=models.Index(fields=['status', 'created_at'], name='core_backen_status_d4d147_idx'),
        ),
        migrations.DeleteModel(
            name='AgentExecutionLog',
        ),
        migrations.DeleteModel(
            name='ReadmeGenerationLog',
        ),
    ]
