# Generated by Django 6.0.4 on 2026-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0003_readmegenerationmonitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmegenerationmonitor',
            name='llm_call_count',
            field=models.IntegerField(default=0),
        ),
    ]
